#!/usr/bin/perl
(sub {
    use strict;
    use warnings;

    my $QD_ARCHIVES = $ENV{'QD_ARCHIVES'};
    if (!($QD_ARCHIVES)) {
        die "uuidgen> no QD_ARCHIVES env variable.\n" .
            "please check your environment settings or reinstall.";
        
    }

    for (my $i = 0; $i <= 0xffffffff; ++$i) {
        #if (-e $QD
        my $tmp = sprintf("%08x", $i); 
        
        unless (-e "$QD_ARCHIVES/$tmp") {
            print "$tmp";
            last;
        }    
    }
})->();



